# Generated by Django 4.1.7 on 2023-06-12 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_save', models.CharField(max_length=50)),
                ('save_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_size', models.FloatField()),
                ('set_name', models.CharField(max_length=50)),
                ('cube_name', models.CharField(max_length=50)),
                ('set_details', models.CharField(max_length=500)),
                ('num_records', models.IntegerField(default=0)),
                ('num_ids', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('save_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('cohort_id', models.AutoField(primary_key=True, serialize=False)),
                ('cohort_size', models.FloatField()),
                ('cohort_name', models.CharField(max_length=20)),
                ('cohort_query_path', models.CharField(max_length=50)),
                ('save_time', models.DateTimeField(auto_now=True)),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cool_dashboard.dataset')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(max_length=50)),
                ('analysis_save', models.CharField(max_length=50)),
                ('analysis_type', models.CharField(max_length=50)),
                ('save_time', models.DateTimeField(auto_now=True)),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cool_dashboard.dataset')),
            ],
        ),
    ]
