# Generated by Django 4.1.7 on 2023-05-02 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_save', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='csv_file',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_size', models.FloatField()),
                ('file_name', models.CharField(max_length=50)),
                ('file_save', models.CharField(max_length=50)),
                ('num_records', models.IntegerField(default=0)),
                ('num_ids', models.IntegerField(default=0)),
                ('involved_dates', models.CharField(default='', max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(max_length=50)),
                ('analysis_save', models.CharField(max_length=50)),
                ('analysis_type', models.CharField(max_length=50)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cool_dashboard.csv_file')),
            ],
        ),
    ]
