# Generated by Django 4.1.7 on 2023-05-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='save_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='csv_file',
            name='save_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='upload_history',
            name='save_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
