# Generated by Django 4.1.7 on 2023-05-14 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cool_dashboard', '0002_analysis_save_time_csv_file_save_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cube_details',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('cube_size', models.FloatField()),
                ('set_name', models.CharField(max_length=50)),
                ('cube_name', models.CharField(max_length=50)),
                ('set_details', models.CharField(max_length=500)),
                ('num_records', models.IntegerField(default=0)),
                ('num_ids', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('save_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='analysis',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cool_dashboard.cube_details'),
        ),
        migrations.DeleteModel(
            name='csv_file',
        ),
    ]
