# Generated by Django 4.1.7 on 2023-06-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cool_dashboard', '0003_rename_file_id_dataset_set_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohort',
            old_name='cohort_query_path',
            new_name='query_name',
        ),
    ]
