# Generated by Django 4.1.7 on 2023-06-12 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cool_dashboard', '0004_rename_cohort_query_path_cohort_query_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='query_name',
        ),
        migrations.AlterField(
            model_name='cohort',
            name='cohort_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_name', models.CharField(max_length=50)),
                ('save_time', models.DateTimeField(auto_now=True)),
                ('exe_time', models.FloatField()),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cool_dashboard.dataset')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='query_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cool_dashboard.query'),
            preserve_default=False,
        ),
    ]
