# Generated by Django 4.1.7 on 2023-06-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool_dashboard', '0005_remove_cohort_query_name_alter_cohort_cohort_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='cohort_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
