# Generated by Django 4.1.7 on 2023-06-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool_dashboard', '0006_alter_cohort_cohort_name_alter_query_query_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_name',
            field=models.CharField(max_length=50),
        ),
    ]
