# Generated by Django 4.1.7 on 2023-06-15 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cool_dashboard', '0007_alter_query_query_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_mode',
            field=models.CharField(choices=[('CC', 'Cohort-Create'), ('CA', 'Cohort-Analysis'), ('OS', 'Others')], default='OS', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='query',
            unique_together={('query_name', 'user_id', 'set_id')},
        ),
    ]
